# Generated by Django 3.2.20 on 2023-08-17 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workflow_settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField()),
                ('splitting_ratio_labeled_test', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contributors', models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_creator', to=settings.AUTH_USER_MODEL), related_name='workflow_contributors', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
                'unique_together': {('title', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='Labelfunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=workflow_settings.models.upload_to_labelfunction)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_settings.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=workflow_settings.models.upload_to_file)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_creator', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_settings.workflow')),
            ],
        ),
    ]
