# Generated by Django 3.2.20 on 2023-08-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelfunction',
            old_name='title',
            new_name='name',
        ),
    ]
