# Generated by Django 3.2.20 on 2023-08-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='splitting_ratio_labeled_test',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=4),
        ),
    ]
