# Generated by Django 3.2.20 on 2023-07-26 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow_settings', '0002_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='workflow',
            name='contributors',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_creator', to=settings.AUTH_USER_MODEL), related_name='workflow_contributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('title', 'creator')},
        ),
    ]
