# Generated by Django 3.2.20 on 2023-08-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0002_rename_title_labelfunction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelfunction',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
