# Generated by Django 3.2.20 on 2023-08-08 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0003_auto_20230726_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_id', models.IntegerField()),
                ('tweet_id', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=400)),
                ('splitting', models.CharField(choices=[('D', 'Development'), ('T', 'Test'), ('U', 'Unlabeled')], default='U', max_length=1)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_settings.workflow')),
            ],
        ),
    ]
