# Generated by Django 3.2.20 on 2023-10-16 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow_settings', '0003_alter_labelfunction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('labelmatrix', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labelfunction_creator_run', to=settings.AUTH_USER_MODEL)),
                ('labelfunctions', models.ManyToManyField(to='workflow_settings.Labelfunction')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_settings.workflow')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.DeleteModel(
            name='Labelfunction_Run',
        ),
    ]
