# Generated by Django 3.2.20 on 2023-10-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0004_auto_20231016_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='splitting_ratio_labeled_test',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=4),
        ),
    ]
