# Generated by Django 3.2.20 on 2023-10-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0005_run_splitting_ratio_labeled_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='used_file',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='workflow_settings.file'),
        ),
    ]
