# Generated by Django 3.2.20 on 2023-11-04 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0007_remove_workflow_splitting_ratio_labeled_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='used_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_settings.file'),
        ),
        migrations.AlterUniqueTogether(
            name='labelfunction',
            unique_together={('workflow', 'name')},
        ),
    ]
