# Generated by Django 3.2.20 on 2023-11-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0008_auto_20231104_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='used_file',
        ),
    ]
