# Generated by Django 3.2.20 on 2023-11-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0009_remove_run_used_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='splitting_ratio_labeled_test',
        ),
    ]
