# Generated by Django 3.2.20 on 2023-11-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0011_run_labelfunction_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='labelfunction_reference',
            new_name='labelfunction_summary',
        ),
    ]
