# Generated by Django 3.2.20 on 2023-11-19 22:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0012_rename_labelfunction_reference_run_labelfunction_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_summary', models.TextField(null=True)),
                ('type', models.CharField(choices=[('M', 'Majority Vote'), ('P', 'Probabilistic')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BW', 'Bag of Words'), ('TF', 'tfidf')], max_length=2)),
                ('features', models.TextField()),
                ('range_x', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('range_y', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_settings.run')),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='labelsummary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_settings.labelsummary'),
        ),
    ]
