# Generated by Django 3.2.20 on 2023-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0014_auto_20231119_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='features',
        ),
        migrations.AddField(
            model_name='feature',
            name='features_test',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='features_train',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='features_unlabeled',
            field=models.TextField(null=True),
        ),
    ]
