# Generated by Django 3.2.20 on 2023-11-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0015_auto_20231119_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='run',
        ),
        migrations.AddField(
            model_name='run',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_settings.feature'),
        ),
    ]
