# Generated by Django 3.2.20 on 2023-12-11 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0016_auto_20231120_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NB', 'Naive Bayes')], max_length=2)),
                ('test_score', models.DecimalField(decimal_places=9, max_digits=10)),
                ('train_score', models.DecimalField(decimal_places=9, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='features_test',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='features_train',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='features_unlabeled',
        ),
        migrations.RemoveField(
            model_name='labelsummary',
            name='label_summary',
        ),
        migrations.AddField(
            model_name='run',
            name='classifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_settings.classifier'),
        ),
    ]
