# Generated by Django 3.2.20 on 2023-12-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0017_auto_20231211_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='labelfunction_summary_train',
            field=models.TextField(null=True),
        ),
    ]
