# Generated by Django 3.2.20 on 2024-02-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0018_run_labelfunction_summary_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
