# Generated by Django 3.2.20 on 2024-04-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0019_workflow_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='preds_unlabeled',
            field=models.TextField(null=True),
        ),
    ]
