# Generated by Django 3.2.20 on 2024-04-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0021_rename_labelsummary_run_labelmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='type',
            field=models.CharField(choices=[('NB', 'Naive Bayes'), ('RF', 'Random Forest'), ('DT', 'Decision Tree'), ('KN', 'KNeighbors'), ('LR', 'Logistic Regression')], max_length=2),
        ),
    ]
