# Generated by Django 3.2.20 on 2024-05-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0023_remove_workflow_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelfunction',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='labelfunction',
            name='results',
            field=models.TextField(null=True),
        ),
    ]
