# Generated by Django 3.2.20 on 2024-05-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0024_auto_20240508_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelfunction',
            old_name='results',
            new_name='summary_train',
        ),
        migrations.AddField(
            model_name='labelfunction',
            name='summary_unlabeled',
            field=models.TextField(null=True),
        ),
    ]
