# Generated by Django 3.2.20 on 2024-06-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_settings', '0026_classifiermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassifierModel',
        ),
    ]
